sudo: false
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn add --force node-sass
  - yarn build
  - yarn preDeploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master