sudo: false
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn add --force node-sass
  -yarn build
  - yarn preDeploy

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
local_dir: dist
on:
  branch: master